### ISSUE TITLE
Name of the font

### ISSUE THREAD

**Issue by misterioss** [juliettepretot/lucy-vscode-theme#4]
What's a name of the font on the screenshot? 
Thanks for the great theme :)

**Comment by chipsld** [comment]
> What's a name of the font on the screenshot?
> Thanks for the great theme :)

if i'm not mistaken its  : Inconsolata

**Comment by chipsld** [comment]
> What's a name of the font on the screenshot?
> Thanks for the great theme :)

If i'm not mistaken its : Iosevka
